### ISSUE TITLE
US-1.1 - Cytoscape Reporting System Access

### ISSUE THREAD

**Issue by kemaric** [Swen670Grp1/cytoscape-platform-tests-js#18]
User Story: As a user, I want to have the access of Cytoscape Defect Reporting System so that I can able to use the system.

AC_01: Give the user name and password, when I enter the credential, then application should take it to Cytoscape Defect Reporting System.

Related Req:
REQ 1.6 - The system shall allow the user to report a defect into Cytoscape Defect Reporting System.

**Comment by kouissar** [comment]
This has been addressed via US 1.2.
